version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: agriprice-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - agriprice-network

  backend:
    build: ./backend
    container_name: agriprice-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/agriprice
    volumes:
      - ./backend:/app
    networks:
      - agriprice-network

  mongo:
    image: mongo:6
    container_name: agriprice-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - agriprice-network

volumes:
  mongo-data:

networks:
  agriprice-network: