version: "3.8"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agriprice_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - agriprice-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agriprice_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/agriprice
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - agriprice-network

  mongo:
    image: mongo:6
    container_name: agriprice-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - agriprice-network

volumes:
  mongo-data:

networks:
  agriprice-network:
    driver: bridge