<<<<<<< HEAD
name: Build Step

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build project
      run: npm run build
=======
name: Build Step

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build project
      run: npm run build
>>>>>>> 24482f2 (feat: initial clean deploy with working backend and port fixes)
      shell: bash