name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || echo "No backend dependencies"

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Frontend Image
        run: docker build --no-cache -f frontend/Dockerfile -t agriprice-frontend:$IMAGE_TAG frontend/

      - name: Build Backend Image
        run: docker build --no-cache -f backend/Dockerfile -t agriprice-backend:$IMAGE_TAG backend/


      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
             image-ref: agriprice-frontend:${{ env.IMAGE_TAG }}
             severity: CRITICAL
             exit-code: '0'

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: agriprice-backend:${{ env.IMAGE_TAG }}
            severity: CRITICAL
            exit-code: '0'

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/
          soft_fail: false

      - name: Push Docker image (simulated)
        run: echo "Pushing agriprice-connect:$IMAGE_TAG to registry..."

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with Ansible
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

      