name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || echo "No backend dependencies"

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --no-cache -t agriprice-connect:$IMAGE_TAG ./frontend


      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: agriprice-connect:${{ env.IMAGE_TAG }}
          severity: CRITICAL
          exit-code: '0'   # allow pass but still scan

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/
          soft_fail: false

      - name: Push Docker image (simulated)
        run: echo "Pushing agriprice-connect:$IMAGE_TAG to registry..."

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with Ansible
        run: ansible-playbook -i inventory.ini deploy.yml