name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/ci-pipeline", "test/ci-failure" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #  Skip Node steps 
      - name: Skip install
        run: echo "No Node project found, skipping npm install"

      # Run tests
      - name: Run tests
        uses: ./pipelines/templates/test.yml

      #  Docker build 
      - name: Build Docker images
        run: docker compose build