name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/ci-pipeline", "test/ci-failure" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies 
      - name: Install dependencies
        run: npm install

      #  Run tests 
      - name: Run tests
        uses: ./pipelines/templates/test.yml

      # Build project
      - name: Build project
        run: npm run build || echo "No build step"

      # Docker
      - name: Build Docker images
        run: docker compose build