name: CI Pipeline

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check HTML files
        run: echo "HTML check passed"

      - name: Check CSS files
        run: echo "CSS check passed"

      - name: Run basic test
        run: echo "Basic test successful"

      - name: Check if Dockerfile exists
        run: | 
            if [ -f Dockerfile ]; then
             docker build -t crop-price-tracker .
            else
             echo "Dockerfile not found yet, skipping build"
             fi