name: Docker Build

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image 
        run: docker build --no-cache -t agriprice-connect ./frontend