name: Security Checks

on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: agriprice-connect
          severity: CRITICAL
          exit-code: '0'

      - name: Run tfsec (IaC security scan)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/
          soft_fail: false